import { formatUiText, clampLevelIndex, validateLevelData } from '../utils/gameHelpers.js';
import { levels as realLevels, type LevelConfig } from '../data/levels.js';
import { dialogues as realDialogues } from '../data/dialogue.js';

// --- Tiny assertion helper & test harness for Node execution ----------------
// When this file is pasted into Vitest/Jest, the real globals take over.

declare const process: { exit(code?: number): void } | undefined;

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== typeof b) return false;
  if (typeof a !== 'object' || a === null || b === null) return false;

  const aArr = Array.isArray(a);
  const bArr = Array.isArray(b);
  if (aArr !== bArr) return false;

  if (aArr) {
    const aa = a as unknown[];
    const bb = b as unknown[];
    if (aa.length !== bb.length) return false;
    return aa.every((item, i) => deepEqual(item, bb[i]));
  }

  const aObj = a as Record<string, unknown>;
  const bObj = b as Record<string, unknown>;
  const aKeys = Object.keys(aObj);
  const bKeys = Object.keys(bObj);
  if (aKeys.length !== bKeys.length) return false;
  return aKeys.every((key) => deepEqual(aObj[key], bObj[key]));
}

function expect(actual: unknown) {
  return {
    toBe(expected: unknown) {
      if (actual !== expected) {
        throw new Error(
          `expected ${JSON.stringify(expected)} to be ${JSON.stringify(actual)}`
        );
      }
    },
    toEqual(expected: unknown) {
      if (!deepEqual(actual, expected)) {
        throw new Error(
          `expected ${JSON.stringify(expected)} to equal ${JSON.stringify(actual)}`
        );
      }
    },
    toContain(item: unknown) {
      const itemStr = typeof item === 'string' ? item : JSON.stringify(item);
      if (typeof actual === 'string') {
        if (!actual.includes(itemStr)) {
          throw new Error(
            `expected ${JSON.stringify(actual)} to contain ${JSON.stringify(item)}`
          );
        }
        return;
      }
      if (!Array.isArray(actual) || !actual.includes(item)) {
        throw new Error(
          `expected ${JSON.stringify(actual)} to contain ${JSON.stringify(item)}`
        );
      }
    },
  };
}

type TestFn = () => void | Promise<void>;

let passed = 0;
let failed = 0;

const runIt = (name: string, fn: TestFn) => {
  try {
    const result = fn();
    if (result instanceof Promise) {
      result.then(
        () => {
          passed++;
          console.log(`  ✓ ${name}`);
        },
        (err: unknown) => {
          failed++;
          console.error(`  ✗ ${name}`);
          console.error('   ', err instanceof Error ? err.message : err);
        }
      );
      return;
    }
    passed++;
    console.log(`  ✓ ${name}`);
  } catch (err) {
    failed++;
    console.error(`  ✗ ${name}`);
    console.error('   ', err instanceof Error ? err.message : err);
  }
};

const runDescribe = (name: string, fn: () => void) => {
  console.log(name);
  fn();
};

const it = ((globalThis as Record<string, unknown>).it as typeof runIt) ?? runIt;
const describe =
  ((globalThis as Record<string, unknown>).describe as typeof runDescribe) ?? runDescribe;

// --- Texture catalogue generated by BootScene --------------------------------

const realTextures = [
  'george',
  'bubble',
  'npc_snail',
  'snail',
  'npc_sponge',
  'sponge',
  'npc_fish',
  'npc_frog',
  'frog',
  'wall',
  'plant',
  'drain',
  'background_tank',
  'background_barrel',
  'background_sink',
  'bg_strange_tank',
  'bg_rain_barrel',
  'bg_kitchen_sink',
  'bg_homecoming',
];

// --- Tests -------------------------------------------------------------------

describe('gameHelpers', () => {
  describe('formatUiText', () => {
    it('formats the level name and remaining bubble count', () => {
      expect(formatUiText('Strange Tank', 3)).toBe('Level: Strange Tank\nBubbles: 3');
    });

    it('formats zero bubbles correctly', () => {
      expect(formatUiText('Homecoming', 0)).toBe('Level: Homecoming\nBubbles: 0');
    });
  });

  describe('clampLevelIndex', () => {
    it('clamps negative indexes to 0', () => {
      expect(clampLevelIndex(-1, 4)).toBe(0);
    });

    it('clamps too-high indexes to the last valid index', () => {
      expect(clampLevelIndex(10, 4)).toBe(3);
    });

    it('keeps valid indexes unchanged', () => {
      expect(clampLevelIndex(2, 5)).toBe(2);
    });

    it('returns 0 when no levels are available', () => {
      expect(clampLevelIndex(5, 0)).toBe(0);
    });
  });

  describe('validateLevelData', () => {
    const textures = ['bg_strange_tank', 'snail', 'drain'];

    const baseLevel: LevelConfig = {
      id: 99,
      name: 'Test Tank',
      backgroundKey: 'bg_strange_tank',
      width: 800,
      height: 600,
      playerStart: { x: 400, y: 300 },
      walls: [],
      bubbles: [],
      npcs: [{ x: 100, y: 100, texture: 'snail', dialogKey: 'snail_intro' }],
    };

    it('returns no errors for a valid level', () => {
      expect(validateLevelData([baseLevel], realDialogues, textures)).toEqual([]);
    });

    it('reports a missing backgroundKey', () => {
      const bad = { ...baseLevel, backgroundKey: 'missing_bg' };
      const errors = validateLevelData([bad], realDialogues, textures);
      expect(errors.length).toBe(1);
      expect(errors[0]).toContain('missing background texture');
      expect(errors[0]).toContain('missing_bg');
    });

    it('reports a missing NPC texture', () => {
      const bad: LevelConfig = {
        ...baseLevel,
        npcs: [{ x: 0, y: 0, texture: 'missing_npc', dialogKey: 'snail_intro' }],
      };
      const errors = validateLevelData([bad], realDialogues, textures);
      expect(errors.some((e) => e.includes('missing NPC texture'))).toBe(true);
      expect(errors.some((e) => e.includes('missing_npc'))).toBe(true);
    });

    it('reports a missing dialogKey', () => {
      const bad: LevelConfig = {
        ...baseLevel,
        npcs: [{ x: 0, y: 0, texture: 'snail', dialogKey: 'no_such_dialog' }],
      };
      const errors = validateLevelData([bad], realDialogues, textures);
      expect(errors.some((e) => e.includes('missing dialog key'))).toBe(true);
      expect(errors.some((e) => e.includes('no_such_dialog'))).toBe(true);
    });

    it('reports a playerStart position out of bounds', () => {
      const bad = { ...baseLevel, playerStart: { x: 900, y: 700 } };
      const errors = validateLevelData([bad], realDialogues, textures);
      expect(errors.some((e) => e.includes('playerStart out of bounds'))).toBe(true);
    });

    it('validates the shipped levels, dialogues and textures without errors', () => {
      expect(validateLevelData(realLevels, realDialogues, realTextures)).toEqual([]);
    });
  });
});

// --- Local runner summary ----------------------------------------------------

if (!(globalThis as Record<string, unknown>).describe) {
  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed > 0) {
    (globalThis as { process?: { exit(code?: number): void } }).process?.exit?.(1);
  }
}
